# configs/model/cnn_simplecifar100.yaml
_target_: src.models.cnn.SimpleCNN
num_classes: 100
input_channels: 3

# Architecture
conv_channels: [32, 64]
conv_kernel_size: 3
conv_padding: 1
pool_size: 2

# Dense layers
hidden_dim: 128
dropout_rate: 0.5

# Training
learning_rate: 0.001
optimizer: adam
weight_decay: 1e-4

