# configs/training/cifar100_basic.yaml
max_epochs: 50
patience: 5
min_delta: 0.001

# Learning rate scheduling
lr_scheduler: step
lr_step_size: 7
lr_gamma: 0.1

# Validation
validation_split: 0.0  # Using data module's split
check_val_every_n_epoch: 1

# Logging
log_every_n_steps: 5
save_top_k: 3

# Hardware
accelerator: auto
devices: 1


